# Regression Models Course Project Report
## Martin Hediger

### Exploratory Analysis
In an exploratory analysis sense, first we have a look at the data.
```{r fig.height=5, fig.width=10, echo=, echo=F, warning=F}
p1 <- ggplot(mtcars,
        aes(wt, mpg, col=factor(mtcars$am, levels=0:1, labels=c("Auto", "Man"))))
p1 <- p1 + geom_boxplot(position="dodge")
p1 <- p1 + theme(legend.position="bottom")
p1 <- p1 + scale_color_discrete(name="Transmission Type")

p2 <- ggplot(mtcars, aes(wt, mpg))
p2 <- p2 + geom_point(aes(color=factor(am, levels=0:1, labels=c("Auto", "Man"))))
p2 <- p2 +theme(legend.position="bottom")
p2 <- p2 + scale_color_discrete(name="Transmission Type")

# http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_(ggplot2)
source("multiplot.R")

multiplot(p1, p2, cols=2)
```

The boxplot shows that most likely the automatic cars have lower MPG (and possibly lower variance in the data).


### Research questions:
1 mpg: Better with automatic or manual?  
2 Quantify mpg difference between automatic and manual transmissions 

### Requirements:
- PDF/R markdown
- ~2 pages main text
- Supporting figures in appendix up to total of 5 pages max (sup + main)
- Appendix: Only figures
- Executive summary
- Upload PDF  

### Criteria:
- Interpretation of coefficients
- Exploratory analysis
- Fit of multiple models and detail strategy for model selection
- Question of interest addressed/Reason why question is not answerable
- Residual plot, diagnostics
- Uncertainty quantification in conclusions/correct inference
- Report briefness
- Executive summary
- Rmd
